_target_: src.models.czii_module_classification.CZIILitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1e-3
  
optimize_config:
  mode: normal

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 5
  num_training_steps: ${trainer.max_epochs}

net:
  _target_: src.models.components.classification_timm_2_5d_lstm.Net
  model_name: resnet34d
  num_classes: ${data.num_classes}
  pretrained: true
  num_lstm_layers: 1

# compile model for faster training with pytorch 2.0
compile: false